"""
AutoInvest - Trading Brain (AI Agent)
Uses OpenRouter as primary LLM provider (configurable model) and
Google Gemini as fallback for market analysis and trading decisions.
"""

from __future__ import annotations

import datetime as _dt
import json
import time
from dataclasses import dataclass, field
from typing import Any

from loguru import logger

from agent.prompts import ANALYSIS_PROMPT_TEMPLATE, SYSTEM_PROMPT
from config import settings


@dataclass
class TradeDecision:
    """Trading decision generated by the agent."""

    symbol: str
    action: str                   # BUY, SELL, HOLD
    confidence: float             # 0-100
    portfolio_percent: float      # % of portfolio to use
    reasoning: str
    stop_loss_pct: float = 3.0
    take_profit_pct: float = 5.0


@dataclass
class AgentResponse:
    """Complete response from the AI agent."""

    decisions: list[TradeDecision] = field(default_factory=list)
    market_outlook: str = ""
    risk_level: str = "MEDIUM"
    raw_response: str = ""
    error: str = ""
    timestamp: str = ""


class TradingBrain:
    """
    The bot's "brain". Uses OpenRouter (primary) or Gemini (fallback) to
    reason about market data and generate trading decisions.
    """

    def __init__(self) -> None:
        # OpenRouter (principal - configurable model)
        self._openrouter = None
        if settings.openrouter_api_key:
            try:
                from openai import OpenAI
                self._openrouter = OpenAI(
                    base_url="https://openrouter.ai/api/v1",
                    api_key=settings.openrouter_api_key,
                )
                logger.info(f"OpenRouter configurado como principal (modelo: {settings.openrouter_model})")
            except Exception as exc:
                logger.warning(f"No se pudo inicializar OpenRouter: {exc}")
        else:
            logger.warning("OPENROUTER_API_KEY no configurada.")

        # Gemini (fallback)
        self._client = None
        if settings.gemini_api_key:
            try:
                from google import genai
                self._client = genai.Client(api_key=settings.gemini_api_key)
                logger.info("Gemini configurado como fallback")
            except Exception as exc:
                logger.warning(f"No se pudo inicializar Gemini: {exc}")
        else:
            logger.info("GEMINI_API_KEY no configurada (fallback desactivado)")

        if not self._openrouter and not self._client:
            logger.error("Sin OpenRouter ni Gemini. El agente no podra funcionar.")

        self._decision_history: list[dict[str, Any]] = []

    # ------------------------------------------------------------------
    # Analisis principal
    # ------------------------------------------------------------------

    def analyze_and_decide(
        self,
        portfolio_status: dict[str, Any],
        technical_analysis: dict[str, Any],
        sentiment_data: dict[str, Any],
        tickers: list[dict[str, Any]],
        recent_trades: list[dict[str, Any]],
    ) -> AgentResponse:
        """
        Sends all market data to the LLM and obtains trading decisions.

        Args:
            portfolio_status: Current portfolio state
            technical_analysis: Technical analysis summary per pair
            sentiment_data: Market sentiment data
            tickers: Current prices of all pairs
            recent_trades: Latest executed trades

        Returns:
            AgentResponse with decisions
        """
        if not self._openrouter and not self._client:
            return AgentResponse(error="No LLM configured (neither OpenRouter nor Gemini)")

        timestamp = _dt.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

        # Format technical analysis as readable text
        ta_text = self._format_technical_analysis(technical_analysis)

        # Format raw news headlines for LLM interpretation
        news_text = self._format_news_headlines(sentiment_data)

        # Build context prompt
        user_prompt = ANALYSIS_PROMPT_TEMPLATE.format(
            timestamp=timestamp,
            portfolio_status=json.dumps(portfolio_status, indent=2, default=str),
            technical_analysis=ta_text,
            sentiment_data=json.dumps(sentiment_data, indent=2, default=str),
            news_headlines=news_text,
            tickers=json.dumps(tickers, indent=2, default=str),
            recent_trades=json.dumps(recent_trades[-10:], indent=2, default=str),
        )

        # --- Try OpenRouter first (primary) ---
        if self._openrouter:
            result = self._try_openrouter(user_prompt, timestamp)
            if result:
                return result

        # --- Fallback: Gemini ---
        if self._client:
            result = self._try_gemini(user_prompt, timestamp)
            if result:
                return result

        return AgentResponse(error="All LLM providers failed")

    # ------------------------------------------------------------------
    # Proveedores LLM
    # ------------------------------------------------------------------

    def _try_gemini(self, user_prompt: str, timestamp: str) -> AgentResponse | None:
        """Fallback: Gemini API."""
        from google.genai import types

        models = [settings.gemini_model, "gemini-2.5-flash-lite"]

        for model_name in models:
            for attempt in range(3):
                try:
                    logger.info(f"Consultando Gemini ({model_name}, intento {attempt + 1})...")
                    response = self._client.models.generate_content(
                        model=model_name,
                        contents=user_prompt,
                        config=types.GenerateContentConfig(
                            system_instruction=SYSTEM_PROMPT,
                            temperature=settings.llm_temperature,
                            top_p=settings.llm_top_p,
                            top_k=settings.llm_top_k,
                            max_output_tokens=settings.llm_max_tokens,
                        ),
                    )
                    raw_text = response.text.strip()
                    return self._finalize_response(raw_text, timestamp)

                except Exception as exc:
                    wait = (attempt + 1) * 5
                    logger.warning(f"Error Gemini ({model_name}): {exc}. Reintentando en {wait}s...")
                    time.sleep(wait)

        logger.error("Gemini agotado.")
        return None

    def _try_openrouter(self, user_prompt: str, timestamp: str) -> AgentResponse | None:
        """Primary: OpenRouter (OpenAI-compatible API, configurable model)."""
        model = settings.openrouter_model
        for attempt in range(3):
            try:
                logger.info(f"Consultando OpenRouter ({model}, intento {attempt + 1})...")
                response = self._openrouter.chat.completions.create(
                    model=model,
                    messages=[
                        {"role": "system", "content": SYSTEM_PROMPT},
                        {"role": "user", "content": user_prompt},
                    ],
                    temperature=settings.llm_temperature,
                    top_p=settings.llm_top_p,
                    max_tokens=settings.llm_max_tokens,
                )
                raw_text = response.choices[0].message.content.strip()
                logger.info(f"Respuesta de OpenRouter [{model}] ({len(raw_text)} chars)")
                return self._finalize_response(raw_text, timestamp)

            except Exception as exc:
                wait = (attempt + 1) * 5
                logger.warning(f"Error OpenRouter: {exc}. Reintentando en {wait}s...")
                time.sleep(wait)

        logger.warning("OpenRouter agotado. Pasando a Gemini...")
        return None

    def _finalize_response(self, raw_text: str, timestamp: str) -> AgentResponse:
        """Parsea y guarda la respuesta del LLM."""
        agent_response = self._parse_response(raw_text)
        agent_response.timestamp = timestamp

        self._decision_history.append({
            "timestamp": timestamp,
            "decisions": [
                {"symbol": d.symbol, "action": d.action, "confidence": d.confidence}
                for d in agent_response.decisions
            ],
            "market_outlook": agent_response.market_outlook,
        })
        self._decision_history = self._decision_history[-50:]

        return agent_response

    # ------------------------------------------------------------------
    # Parsing de respuesta
    # ------------------------------------------------------------------

    def _parse_response(self, raw: str) -> AgentResponse:
        """Parsea la respuesta JSON del LLM."""
        # Limpiar markdown code blocks si existen
        text = raw
        if "```json" in text:
            text = text.split("```json")[1].split("```")[0]
        elif "```" in text:
            text = text.split("```")[1].split("```")[0]

        try:
            data = json.loads(text.strip())
        except json.JSONDecodeError as exc:
            logger.error(f"Error parseando JSON del agente: {exc}\nRaw: {raw[:500]}")
            return AgentResponse(raw_response=raw, error=f"JSON invalido: {exc}")

        decisions = []
        for d in data.get("decisions", []):
            action = d.get("action", "HOLD").upper()
            if action not in ("BUY", "SELL", "HOLD"):
                action = "HOLD"

            confidence = float(d.get("confidence", 0))
            portfolio_pct = min(float(d.get("portfolio_percent", 3)), settings.max_position_percent)

            decisions.append(TradeDecision(
                symbol=d.get("symbol", ""),
                action=action,
                confidence=confidence,
                portfolio_percent=portfolio_pct,
                reasoning=d.get("reasoning", ""),
                stop_loss_pct=float(d.get("stop_loss_pct", settings.stop_loss_percent)),
                take_profit_pct=float(d.get("take_profit_pct", settings.take_profit_percent)),
            ))

        return AgentResponse(
            decisions=decisions,
            market_outlook=data.get("market_outlook", ""),
            risk_level=data.get("risk_level", "MEDIUM"),
            raw_response=raw,
        )

    # ------------------------------------------------------------------
    # Formateo
    # ------------------------------------------------------------------

    def _format_technical_analysis(self, ta_data: dict[str, Any]) -> str:
        """Formatea el analisis tecnico como texto legible para el LLM."""
        lines = []
        for symbol, summary in ta_data.items():
            if isinstance(summary, dict):
                lines.append(f"\n#### {symbol}")
                lines.append(f"**Senal general**: {summary.get('overall_signal', 'neutral').upper()} "
                           f"(score: {summary.get('overall_score', 0):.3f})")
                for sig in summary.get("signals", []):
                    emoji = "🟢" if sig["signal"] == "buy" else "🔴" if sig["signal"] == "sell" else "⚪"
                    lines.append(f"  {emoji} {sig['name']}: {sig['detail']}")
            else:
                lines.append(f"\n#### {symbol}: {summary}")

        return "\n".join(lines) if lines else "Sin datos de analisis tecnico disponibles."

    def _format_news_headlines(self, sentiment_data: dict[str, Any]) -> str:
        """
        #6 - Formatea titulares de noticias como texto plano para el LLM.
        VADER no entiende jerga financiera, asi que pasamos los titulares crudos
        para que Gemini los interprete con su propio conocimiento del mercado.
        """
        lines = []

        # Noticias positivas segun VADER (pero Gemini debe re-evaluar)
        for n in sentiment_data.get("top_positive_news", []):
            lines.append(f"- [{n.get('source', '?')}] {n.get('title', '')} (VADER: {n.get('score', 0):+.2f})")

        # Noticias negativas segun VADER
        for n in sentiment_data.get("top_negative_news", []):
            lines.append(f"- [{n.get('source', '?')}] {n.get('title', '')} (VADER: {n.get('score', 0):+.2f})")

        if not lines:
            return "Sin noticias recientes disponibles."

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Filtrar decisiones accionables
    # ------------------------------------------------------------------

    def get_actionable_decisions(self, response: AgentResponse) -> list[TradeDecision]:
        """
        Filtra decisiones con confianza suficiente y accion clara.

        #6 - Confianza flexible:
        - >= min_confidence_normal (60%): trade normal (hasta max_position_percent)
        - >= min_confidence_small (50%): trade chico (max 2% del portfolio)
        - < min_confidence_small: descartado
        """
        actionable = []
        for d in response.decisions:
            if d.action not in ("BUY", "SELL") or not d.symbol:
                continue

            # Ventas siempre se permiten con cualquier confianza razonable
            if d.action == "SELL" and d.confidence >= settings.min_confidence_small:
                actionable.append(d)
                logger.info(
                    f"Decision accionable: {d.action} {d.symbol} "
                    f"(confianza: {d.confidence}%, razon: {d.reasoning[:80]})"
                )
                continue

            # Compras con confianza normal
            if d.confidence >= settings.min_confidence_normal:
                actionable.append(d)
                logger.info(
                    f"Decision accionable: {d.action} {d.symbol} "
                    f"(confianza: {d.confidence}%, razon: {d.reasoning[:80]})"
                )

            # Compras con confianza baja -> trade chico (max 2%)
            elif d.confidence >= settings.min_confidence_small:
                d.portfolio_percent = min(d.portfolio_percent, 2.0)
                actionable.append(d)
                logger.info(
                    f"Decision accionable (confianza baja, trade chico): {d.action} {d.symbol} "
                    f"(confianza: {d.confidence}%, max 2%, razon: {d.reasoning[:80]})"
                )
            else:
                logger.debug(
                    f"Decision descartada por baja confianza: {d.action} {d.symbol} "
                    f"(confianza: {d.confidence}%)"
                )

        return actionable

    @property
    def decision_history(self) -> list[dict[str, Any]]:
        return self._decision_history.copy()
